# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"          # location of requirements.txt
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels: ["dependencies"]
