# docker-compose.yml
services:
  # NEW: The PostgreSQL Database Service
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The Mosquitto MQTT Broker Service (Unchanged)
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"

  # Our Aegis Event Bus Service (Updated depends_on)
  eventbus:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      # We keep the old SQLite volume for now. The app will still use it.
      - ./projects_data:/app/projects_data
      - ./eventbus.db:/app/eventbus.db
    depends_on:
      mosquitto:
        condition: service_started
      # NEW: This line tells our app to wait for Postgres to be healthy
      postgres:
        condition: service_healthy

volumes:
  postgres_data: