# docker-compose.yml
services:
  # The Mosquitto MQTT Broker Service
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"

  # Our Aegis Event Bus Service
  eventbus:
    build: .
    ports:
      - "8000:8000"
    # This makes the .env file available inside the container
    env_file:
      - .env
    volumes:
      # This is the key part for SQLite: it shares your local files
      # with the container so it can read/write to them.
      - ./projects_data:/code/projects_data
      - ./eventbus.db:/code/eventbus.db
    depends_on:
      - mosquitto