# .github/workflows/ci.yml — lint/tests, PG integration test, SBOM
name: Aegis CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt pre-commit
      - run: pre-commit run --all-files
      - run: pytest -q

  integration-postgres:
    needs: lint-test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres
      PG_TRIGGER_TEST_DSN: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: echo "DATABASE_URL=$DATABASE_URL"; echo "PG_TRIGGER_TEST_DSN=$PG_TRIGGER_TEST_DSN"
      - run: alembic upgrade head
      - run: pytest -k hash_integrity -v

  sbom:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install cyclonedx-bom
      # Prefer the lock file for reproducibility; fall back to requirements.txt if you ever drop the lock.
      - run: cyclonedx-py requirements -r requirements.lock -o sbom.xml
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
