name: Aegis CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt pre-commit
      - run: pre-commit run --all-files
      - run: pytest -q

  integration-postgres:
    needs: lint-test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    env:
      # One place to define DSN for BOTH alembic and the test
      PG_TRIGGER_TEST_DSN: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Show DSNs (masked values will appear as ***)
        run: |
          echo "PG_TRIGGER_TEST_DSN=$PG_TRIGGER_TEST_DSN"
          echo "DATABASE_URL=$DATABASE_URL"
      - name: Run migrations
        run: alembic upgrade head
      - name: Run ONLY the trigger test on PG
        run: pytest -k hash_integrity -v
